name: {{name.snakeCase()}}_example
description: "{{description}}"
version: 1.0.0
publish_to: 'none'


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serinus: ^{{serinus_version}}
  {{name.snakeCase()}}: ^{{version}}
  
